version: 2
jobs:
  build:
    docker:
      - image: macnicadevops/cci-build-jfrog:0.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build -t "docker-local."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .
            docker images
            dockerd --insecure-registry=jfrog-lb-04101d2dd53d370e.elb.us-west-1.amazonaws.com
            docker login jfrog-lb-04101d2dd53d370e.elb.us-west-1.amazonaws.com -u ozawa -p xaJel4KO

      #- run:
      #    name: Login and Publish
      #    command: |
      #      docker login $repo  -u $user -p $password
      #      docker push "docker."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM

      #- run:
      #    name: Request for scan build
      #    command: |
      #      echo '{"artifactoryId": "'$jid'","buildName": "'$CIRCLE_PROJECT_REPONAME'","buildNumber": "'$CIRCLE_BUILD_NUM'"}' > temp.json
      #      curl -X POST -u $user":"$password -H "Content-Type: application/json" $xurl"/api/v1/scanBuild" -d @temp.json 
      - run:
          name: JFrogCLI config
          command: |
            /./jfrog rt config --user=$user --password=$password --url="http://"$jfqdn"/artifactory" $jid
            /./jfrog rt ping
      - run:
          name: JFrogCLI artifact publish
          command: |
           /./jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /./jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /./jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /./jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /./jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM docker-local
           /./jfrog rt dp "docker-local."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM docker-local --build-name=my-build-name --build-number=7

